sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t prashplus/test /home/travis/build/prashplus/containernet-docker
  - docker run -d --name test -it prashplus/test /bin/sh

script:
  - docker ps -a