sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t prashplus/test /home/travis/build/prashplus/containernet-docker
  - docker run -d --name test --privileged -it -v /home/travis/build/prashplus/containernet-docker/script:/script prashplus/test /bin/bash

script:
  - docker ps -a